Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  #
  # Run Ansible from the Vagrant Host
  #
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "install_docker.yml"
  end
end