apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-app-deployment
  labels:
    app: time_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: time_app
  template:
    metadata:
      labels:
        app: time_app
    spec:
      containers:
      - name: moscow-time
        image: validolchik/moscow_time:latest
        ports:
        - containerPort: 5000