#global config
global:
  scrape_interval: 15s
  evaluation_interval: 5s
  scrape_timeout: 4s
  #query_log_file: <string>
  external_labels:
    monitor: "codelab-monitor"
# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: "prometheus"
    # Override the global default and scrape targets from job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "loki"
    scrape_interval: 5s
    static_configs:
      - targets:
          - loki:3100
