---
- hosts: app_server
  remote_user: ansible_worker
  vars:
    username: ansible_worker
    docker_hub_app_tag: latest

  roles:
    - role: docker_install
      become: true
      vars:
        docker_users:
          - "{{ username }}"
    - role: app_python_install
      python_app_tag: "{{ docker_hub_app_tag }}"